### PR TITLE
Updated contact

### PR DESCRIPTION
**Pull request by nlharris**
added author
incremented version #

### CODE REVIEW

**Comment by MrCreosote** [comment]
Are these fields even used any more? I thought the kbase.yml file superseded the author and version in the spec.json file. If they don't, we have two sources of truth which is bad.

If the contact field is just always going to be the contact me form, it seems to me we should just ignore it in the UI and remove it from the spec.json file.

**Comment by MrCreosote** [comment]
@msneddon @rsutormin ?

**Comment by nlharris** [comment]
> If the contact field is just always going to be the contact me form, it seems to me we should just ignore it in the UI and remove it from the spec.json file.
Fine with me--it's tedious changing them in all the spec files.

**Comment by MrCreosote** [comment]
As far as I can tell, none of these fields are actually used in the UI. @eapearson @briehl can you confirm?

**Comment by sychan** [comment]
Just going to merge this to clear it out. If it isn't used, this is a no-op, if it is used it is useful

**Pull request merged**
